import QtQuick
import Quickshell

Singleton {
    readonly property color primary: "#b4befe"
    readonly property color secondary: "#cba6f7"
    readonly property color accent: "#f5c2e7"
    readonly property color background: "#1e1e2e"
    readonly property color surface: "#313244"
    readonly property color surfaceVariant: "#45475a"
    readonly property color onPrimary: "#11111b"
    readonly property color onSecondary: "#11111b"
    readonly property color onAccent: "#11111b"
    readonly property color onBackground: "#cdd6f4"
    readonly property color onSurface: "#cdd6f4"
    readonly property color onSurfaceVariant: "#bac2de"
    readonly property color text: "#cdd6f4"
    readonly property color textSecondary: "#bac2de"
    readonly property color textMuted: "#a6adc8"
    readonly property color textDisabled: "#6c7086"
    readonly property color border: "#585b70"
    readonly property color borderLight: "#6c7086"
    readonly property color success: "#a6e3a1"
    readonly property color warning: "#f9e2af"
    readonly property color error: "#f38ba8"
    readonly property color info: "#89b4fa"
    readonly property color highlight: "#b4befe"
    readonly property color selection: "#585b70"
    readonly property color hover: "#45475a"
    readonly property color focus: "#b4befe"
    readonly property color disabled: "#6c7086"
    readonly property color shadow: "#11111b"
    readonly property color overlay: "#1e1e2e"
    readonly property color card: "#313244"
    readonly property color cardHover: "#45475a"
    readonly property color button: "#b4befe"
    readonly property color buttonHover: "#cba6f7"
    readonly property color buttonPressed: "#a6adc8"
    readonly property color input: "#313244"
    readonly property color inputBorder: "#585b70"
    readonly property color inputFocus: "#b4befe"
    readonly property color scrollbar: "#45475a"
    readonly property color scrollbarThumb: "#6c7086"
    readonly property color tooltip: "#45475a"
    readonly property color tooltipText: "#cdd6f4"
    readonly property real opacity: 0.8
    readonly property bool enabled: true
}
