# Rose Pine Starship Config - Just enough, not too much
# version: 1.1.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "... "
palette = 'catppuccin-mocha'

format = """$username\
$hostname\
$directory\
$git_branch\
$docker_context\
$kubernetes\
$aws\
$gcloud\
$azure\
$python\
$nodejs\
$rust\
$golang\
$java\
$terraform\
$character"""

right_format = """$cmd_duration\
$git_status\
$time"""

[palettes.catppuccin-mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
success_symbol = "[●](teal)"
error_symbol = "[●](red)"  
vimcmd_symbol = "[●](lavender)" 

[username]
style_user = "fg:lavender"
style_root = "fg:red"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = true 
format = "[ $hostname]($style)"
style = "fg:lavender"

[directory]
truncation_length = 3
truncation_symbol = "…/"
read_only = " [RO]"
format = "[ $path]($style)[](fg:overlay1)[$read_only](fg:red) "
style = "fg:sapphire"

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "fg:teal"
symbol = ""
truncation_length = 20
truncation_symbol = "..."

[git_status]
disabled = false
format = '([$all_status$ahead_behind]($style))'
up_to_date = '[ ✓ ](fg:lavender)'
conflicted = '[!](fg:red)'
untracked = '[?\($count\)](fg:yellow)'
stashed = '[\$](fg:lavender)'
modified = '[*\($count\)](fg:yellow)'
staged = '[+\($count\)](fg:yellow)'
renamed = '[»\($count\)](fg:lavender)'
deleted = '[x\($count\)](fg:red)'
ahead = '[⇡\(${count}\)](fg:teal)'
behind = '[⇣\(${count}\)](fg:rosewater)'
diverged = '⇕[\[⇡\(${ahead_count}\)](fg:teal)[⇣\(${behind_count}\)](fg:rosewater)[\]](fg:lavender)'

[cmd_duration]
min_time = 2000
format = "[ $duration ]($style)"
style = "fg:text"

[time]
disabled = false
format = "[ $time]($style)"
style = "fg:rosewater"
time_format = "%H:%M"

# Language indicators - minimal, no versions but with Rose Pine styling
[python]
format = "[](fg:overlay1)[ py ]($style)[](fg:overlay1) "
style = "fg:sapphire"

[nodejs]
format = "[](fg:overlay1)[ js ]($style)[](fg:overlay1) "
style = "fg:sapphire"
symbol = "󰎙 "

[rust]
format = "[](fg:overlay1)[ rs ]($style)[](fg:overlay1) "
style = "fg:sapphire"
symbol = " "

[golang]
format = "[](fg:overlay1)[ go ]($style)[](fg:overlay1) "
style = "fg:sapphire"
symbol = " "

[java]
format = "[](fg:overlay1)[ java ]($style)[](fg:overlay1) "
style = "fg:sapphire"
symbol = " "

[lua]
format = "[](fg:overlay1)[ lua ]($style)[](fg:overlay1) "
style = "fg:sapphire"

[ruby]
format = "[](fg:overlay1)[ rb ]($style)[](fg:overlay1) "
style = "fg:sapphire"

# Cloud and infrastructure
[terraform]
format = "[](fg:overlay1)[ tf ]($style)[](fg:overlay1) "
style = "fg:sapphire"

[docker_context]
format = "[](fg:overlay1)[ docker ]($style)[](fg:overlay1) "
style = "fg:sapphire"

[kubernetes]
format = "[](fg:overlay1)[ k8s ]($style)[](fg:overlay1) "
style = "fg:sapphire"

[aws]
format = "[](fg:overlay1)[ aws ]($style)[](fg:overlay1) "
style = "fg:sapphire"

[gcloud]
format = "[](fg:overlay1)[ gcp ]($style)[](fg:overlay1) "
style = "fg:sapphire"

[azure]
format = "[](fg:overlay1)[ az ]($style)[](fg:overlay1) "
style = "fg:sapphire"

# Disable everything else
[package]
disabled = true

[battery]
disabled = true

[sudo]
disabled = true

[jobs]
disabled = true

[memory_usage]
disabled = true

[localip]
disabled = true

[shlvl]
disabled = true

[shell]
disabled = true

[container]
disabled = true

[singularity]
disabled = true

[nix_shell]
disabled = true
